# Generated by Django 5.1.4 on 2024-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_concert',
            field=models.DateTimeField(null=True),
        ),
    ]
